### ISSUE TITLE
项目下载下来 运行报错 Uncaught (in promise) Error: Cannot destructure property 'AES' of 'CryptoJS' as it is undefined.     at eval (index.cjs:73:1)

### ISSUE THREAD

**Issue by ZephyrGao** [dvgis/dc-vue#22]
node版本 16.14  20.9.0都尝试过了 都报错
mac和window11 也都尝试过了 依旧报错
<img width="942" alt="QQ20231204-175532@2x" src="https://github.com/dvgis/dc-vue/assets/23555850/6cf71998-b3e7-4649-97f8-c5b7dfd18362">

**Comment by cavencj** [comment]
需要手动按安装一下CryptoJS包
然后设置 DC.__namespace['CryptoJS'] = CryptoJS

**Comment by cavencj** [comment]
sdk问题， 下个版本修复
